#SPDX-License-Identifier: MIT-0
---
# tasks file for sou_podman
# tasks file for build_container
    
- name: Podman install 
  yum:
    name: podmam
    state: present
        
- name: start podman
  service: 
    state: started
    enabled: yes
        
- name: install HaProxy
  yum:
    name: haproxy
    state: present
  when: ansible_host == "192.168.56.2"

