Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.provider "virtualbox"
  config.vm.define "nodo1" do |nodo1|
    nodo1.vm.hostname = "nodo1"
 #   nodo1.vm.network "private_network", ip: "192.168.56.2"
  end

  config.vm.define "nodo2" do |nodo2|
    nodo2.vm.hostname = "nodo2"
#    nodo2.vm.network "private_network", ip: "192.168.56.3"

  end
 
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end



end


